import BlogImage1 from '../assets/img/BlogCoverPic1.png'
import BlogImage2 from '../assets/img/GraysolBlog2.webp'

const data = [
    {
      id: 1,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: true,
      graynews: true,
      image:BlogImage1,
    },
    {
      id: 2,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
      image:BlogImage2,
    },
    {
      id: 3,
      time: '1min',
      title:'aaaaaaaaa',
      feature: true,
      press: true,
      insight: false,
      graynews: true,
      image:BlogImage1,
    },
    {
      id: 4,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 5,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: true,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 6,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 7,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 8,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 9,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: true,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 10,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: true,
      graynews: false,
      image:BlogImage1,
    },
    
  ];
export {data};