

const data = [
    {
      id: 1,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: true,
      graynews: true,
    },
    {
      id: 2,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
    },
    {
      id: 3,
      time: '1min',
      title:'aaaaaaaaa',
      feature: true,
      press: true,
      insight: false,
      graynews: true,
    },
    {
      id: 4,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
    },
    {
      id: 5,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: true,
      graynews: false,
    },
    {
      id: 6,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
    },
    {
      id: 7,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: false,
      graynews: false,
    },
    {
      id: 8,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
    },
    {
      id: 9,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: true,
      graynews: false,
    },
    {
      id: 10,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: true,
      graynews: false,
    },
    
  ];
export {data};