import BlogImage1 from '../assets/img/BlogCoverPic1.png'
import BlogImage2 from '../assets/img/GraysolBlog2.webp'
import ChatgbtImage from '../assets/blog/chatgbt.jpeg'
import AwsImage from '../assets/blog/AwsImage.webp' 

const data = [
    {
      id: 1,
      time: '2min',
      title:'Will Chat-GPT replace programmers?',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
      image:ChatgbtImage,
    },
    {
      id: 2,
      time: '4min',
      title:'How to Host a Python Script on AWS EC2 Server and Run it Automatically.',
      feature: true,
      press: true,
      insight: true,
      graynews: false,
      image:AwsImage,
    },
    {
      id: 3,
      time: '1min',
      title:'aaaaaaaaa',
      feature: true,
      press: true,
      insight: false,
      graynews: true,
      image:BlogImage1,
    },
    {
      id: 4,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 5,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 6,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 7,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: false,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 8,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: true,
      press: true,
      insight: false,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 9,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: false,
      press: false,
      insight: true,
      graynews: false,
      image:BlogImage1,
    },
    {
      id: 10,
      time: '1min',
      title:'Walker Mattox, CEO of Gray Solutions, on Building a Dynamic Team of Solutioneers',
      feature: false,
      press: false,
      insight: true,
      graynews: false,
      image:BlogImage1,
    },
    
  ];
export {data};