import {Header} from "./Header.jsx";
import {Footer} from "./Footer.jsx";
import {HomeBanner} from "./HomeBanner.jsx";
import {Sponsers} from "./Sponsers.jsx";
import {ChooseUs} from "./ChooseUs.jsx";
import {Services} from "./Services.jsx";
import {Certifications} from "./Certifications.jsx";
import {Promise} from "./Promise.jsx";
import {Testimonials} from "./Testimonials.jsx";
import {Help} from "./Help.jsx";
import {Question} from "./Question.jsx";
import {Faq} from "./Faq.jsx";
import {Banner} from "./Banner.jsx";
import {DevelopmentFeatures} from "./DevelopmentFeatures.jsx";
import {ServiceFeatures} from "./ServiceFeatures.jsx";
import {Specialization} from "./Specialization.jsx";
import {ServiceDetails} from "./ServiceDetails.jsx";
import {ServiceWorking} from "./ServiceWorking.jsx";
import {ServiceBenefits} from "./ServiceBenefits.jsx";
import {ContactForm} from "./ContactForm.jsx";
import {AboutPageBanner} from "./AboutPageBanner.jsx";
import {AboutTeamLead} from "./AboutTeamLead.jsx";
import {AboutCompanyStats} from "./AboutCompanyStats.jsx";
import {AboutCompanyVision} from "./AboutCompanyVision.jsx";
import {ContactForm2} from "./ContactForm2.jsx";
import {BlogBanner} from "./BlogBanner.jsx";
import {BlogSection} from "./BlogSection.jsx";
import { PortfolioBanner } from "./PortfolioBanner.jsx";
import { PortfolioSection } from "./PortfolioSection.jsx";

export {Header,Footer,HomeBanner, Sponsers,ChooseUs,Services,Certifications,Promise,Testimonials,Help,Question,Faq,Banner,DevelopmentFeatures,ServiceFeatures,Specialization,ServiceDetails,ServiceWorking,ServiceBenefits,ContactForm, AboutPageBanner, AboutTeamLead,AboutCompanyStats,AboutCompanyVision,ContactForm2,BlogBanner,BlogSection,PortfolioBanner, PortfolioSection}