import Header from "./Header.jsx";
import Footer from "./Footer.jsx";
import Banner from "./Banner.jsx";
import Sponsers from "./Sponsers.jsx";
import ChooseUs from "./ChooseUs.jsx";
import Services from "./Services.jsx";
import Certifications from "./Certifications.jsx";
import Promise from "./Promise.jsx";
import Testimonials from "./Testimonials.jsx";
import Help from "./Help.jsx";
import Question from "./Question.jsx";
import Faq from "./Faq.jsx";
import Banner2 from "./Banner2.jsx";
import DevelopmentFeatures from "./DevelopmentFeatures.jsx";
import Wordpress from "./Wordpress.jsx";
import Specialization from "./Specialization.jsx";
import CustomWordpress from "./CustomWordpress.jsx";
import WordpressWorking from "./WordpressWorking.jsx";
import Benefits from "./Benefits.jsx";
import ContactForm from "./ContactForm.jsx";
import AboutBanner from "./AboutBanner.jsx";
import TeamLead from "./TeamLead.jsx";
import CompanyStats from "./CompanyStats.jsx";
import CompanyVision from "./CompanyVision.jsx";
import ContactForm2 from "./ContactForm2.jsx";
import BlogBanner from "./BlogBanner.jsx";
import BlogSection from "./BlogSection.jsx";

export {Header,Footer,Banner, Sponsers,ChooseUs,Services,Certifications,Promise,Testimonials,Help,Question,Faq,Banner2,DevelopmentFeatures,Wordpress,Specialization,CustomWordpress,WordpressWorking,Benefits,ContactForm, AboutBanner, TeamLead,CompanyStats,CompanyVision,ContactForm2,BlogBanner,BlogSection}